/*
Copyright 2026 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

use crate::virtwl::{
    virtwl_ioctl_dmabuf_sync, virtwl_ioctl_new, virtwl_ioctl_recv, virtwl_ioctl_send,
    virtwl_ioctl_txn, DMA_BUF_SYNC_END, DMA_BUF_SYNC_READ, DMA_BUF_SYNC_WRITE,
    VIRTWL_SEND_MAX_ALLOCS,
};
use std::collections::HashSet;
use std::fs::{File, OpenOptions};
use std::io;
use std::os::fd::{AsRawFd, FromRawFd, OwnedFd, RawFd};
use std::os::unix::fs::OpenOptionsExt;
use std::path::Path;
use tokio::io::unix::AsyncFd;

const DEFAULT_BUFFER_SIZE: usize = 4096;
// virtwl_ioctl_txn lives at the beginning of the ioctl buffer, so the data
// payload must leave room for its FD array and length field. ChromiumOS uses
// this exact bound in VirtWaylandChannel::max_send_size().
const MAX_SEND_SIZE: usize = DEFAULT_BUFFER_SIZE - std::mem::size_of::<virtwl_ioctl_txn>();

/// Layout returned by `VIRTWL_IOCTL_NEW_DMABUF`.
///
/// The offsets and strides are host-compositor metadata.  They must be used
/// verbatim when constructing the host linux-dmabuf buffer; recomputing them
/// from width/height is incorrect for multi-plane formats and for allocators
/// that add padding.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct VirtWaylandDmabufLayout {
    pub strides: [u32; 3],
    pub offsets: [u32; 3],
}

fn dmabuf_probe_supported(errno: Option<i32>) -> bool {
    // ChromiumOS treats ENOTTY as the one definitive indication that the
    // kernel does not implement VIRTWL_IOCTL_NEW_DMABUF. Other errors (for
    // example EINVAL from the intentionally empty probe metadata) mean the
    // ioctl exists and should not make the channel silently fall back to the
    // slower shared-memory path.
    errno != Some(libc::ENOTTY)
}

fn add_nonblocking_flag(flags: nix::fcntl::OFlag) -> nix::fcntl::OFlag {
    flags | nix::fcntl::OFlag::O_NONBLOCK
}

fn close_raw_fds(fds: &[i32]) {
    let mut seen = HashSet::new();
    for &fd in fds {
        if fd >= 0 && seen.insert(fd) {
            let _ = nix::unistd::close(fd);
        }
    }
}

fn close_returned_fd(fd: i32) {
    if fd >= 0 {
        let _ = nix::unistd::close(fd);
    }
}

fn owned_fds_from_txn(raw_fds: &[i32]) -> io::Result<Vec<OwnedFd>> {
    let mut packed = true;
    let mut seen = HashSet::new();
    let mut received = Vec::new();

    for &fd in raw_fds {
        if fd == -1 {
            packed = false;
            continue;
        }
        if fd < -1 {
            close_raw_fds(raw_fds);
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                "invalid negative virtwl file descriptor",
            ));
        }
        if !packed || !seen.insert(fd) {
            close_raw_fds(raw_fds);
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                "malformed virtwl file descriptor array",
            ));
        }
        received.push(fd);
    }

    Ok(received
        .into_iter()
        .map(|fd| unsafe { OwnedFd::from_raw_fd(fd) })
        .collect())
}

pub struct VirtWaylandChannel {
    // The device file descriptor (/dev/wl0)
    dev_file: File,
    // The context file descriptor created via ioctl
    // We wrap it in AsyncFd for polling
    ctx_fd: AsyncFd<OwnedFd>,
    supports_dmabuf: bool,
}

impl VirtWaylandChannel {
    pub fn new<P: AsRef<Path>>(path: P) -> io::Result<Self> {
        let dev_file = OpenOptions::new()
            .read(true)
            .write(true)
            .custom_flags(libc::O_CLOEXEC)
            .open(path)?;

        // Create context
        let mut new_ctx = crate::virtwl::virtwl_ioctl_new::new_ctx();
        let ioctl_result = unsafe {
            // virtwl_ioctl_new is generated by ioctl_readwrite! and takes *mut T
            virtwl_ioctl_new(dev_file.as_raw_fd(), &mut new_ctx)
        };
        if let Err(error) = ioctl_result {
            // The kernel may fill fd before reporting a later validation
            // error. Treat that descriptor as owned even on failure.
            close_returned_fd(new_ctx.fd);
            return Err(io::Error::from(error));
        }

        let ctx_fd_raw = new_ctx.fd;
        if ctx_fd_raw < 0 {
            return Err(io::Error::other(
                "Invalid fd returned from VIRTWL_IOCTL_NEW_CTX",
            ));
        }

        let ctx_fd = unsafe { OwnedFd::from_raw_fd(ctx_fd_raw) };

        // Probe the optional dmabuf allocation ioctl once per channel. This
        // mirrors ChromiumOS Sommelier's VirtWaylandChannel::init(): virtwl
        // can carry Wayland traffic even when the host kernel only supports
        // shared-memory allocations, so ENOTTY must be treated as a normal
        // capability result rather than a channel-open failure.
        let mut dmabuf_probe = crate::virtwl::virtwl_ioctl_new::new_dmabuf(0, 0, 0);
        let dmabuf_probe_result =
            unsafe { virtwl_ioctl_new(dev_file.as_raw_fd(), &mut dmabuf_probe) };
        let supports_dmabuf = match dmabuf_probe_result {
            Ok(_) if dmabuf_probe.fd >= 0 => {
                close_returned_fd(dmabuf_probe.fd);
                true
            }
            Ok(_) => {
                log::debug!("virtwl dmabuf capability probe returned success without a valid fd");
                false
            }
            Err(error) => {
                // Some virtwl implementations allocate the descriptor before
                // rejecting the zero-sized probe metadata. Never leak that
                // descriptor on the capability-probe error path.
                close_returned_fd(dmabuf_probe.fd);
                let errno = error as i32;
                log::debug!(
                    "virtwl dmabuf capability probe returned errno {} ({})",
                    errno,
                    std::io::Error::from_raw_os_error(errno)
                );
                dmabuf_probe_supported(Some(errno))
            }
        };

        // Set non-blocking on context FD for AsyncFd
        // F_SETFL replaces the complete file-status flag set. Preserve flags
        // inherited from the kernel (for example O_APPEND/O_ASYNC) while
        // adding the non-blocking bit required by AsyncFd.
        let existing_flags =
            nix::fcntl::fcntl(&ctx_fd, nix::fcntl::FcntlArg::F_GETFL).map_err(io::Error::from)?;
        let nonblocking_flags =
            add_nonblocking_flag(nix::fcntl::OFlag::from_bits_truncate(existing_flags));
        nix::fcntl::fcntl(&ctx_fd, nix::fcntl::FcntlArg::F_SETFL(nonblocking_flags))
            .map_err(io::Error::from)?;

        Ok(Self {
            dev_file,
            ctx_fd: AsyncFd::new(ctx_fd)?,
            supports_dmabuf,
        })
    }

    pub fn supports_dmabuf(&self) -> bool {
        self.supports_dmabuf
    }

    pub fn allocate(&self, size: u32) -> io::Result<(OwnedFd, u32)> {
        let mut new_alloc = crate::virtwl::virtwl_ioctl_new::new_alloc(size);
        let ioctl_result = unsafe { virtwl_ioctl_new(self.dev_file.as_raw_fd(), &mut new_alloc) };
        if let Err(error) = ioctl_result {
            close_returned_fd(new_alloc.fd);
            return Err(io::Error::from(error));
        }

        let fd = new_alloc.fd;
        if fd < 0 {
            return Err(io::Error::other(
                "Invalid fd returned from VIRTWL_IOCTL_NEW_ALLOC",
            ));
        }

        Ok((unsafe { OwnedFd::from_raw_fd(fd) }, size))
    }

    /// Allocate a host-backed PRIME dma-buf and return the layout selected by
    /// the host allocator.
    ///
    /// The returned descriptor is mapped into the guest by the VirtWL kernel
    /// driver.  It can be sent to the host compositor as a linux-dmabuf plane
    /// descriptor and can be CPU-accessed after a `sync` begin operation.
    pub fn allocate_dmabuf(
        &self,
        width: u32,
        height: u32,
        format: u32,
    ) -> io::Result<(OwnedFd, VirtWaylandDmabufLayout)> {
        if width == 0 || height == 0 {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                "VirtWL dma-buf dimensions must be non-zero",
            ));
        }

        let mut new_dmabuf = crate::virtwl::virtwl_ioctl_new::new_dmabuf(width, height, format);
        let ioctl_result =
            unsafe { crate::virtwl::virtwl_ioctl_new(self.dev_file.as_raw_fd(), &mut new_dmabuf) };
        if let Err(error) = ioctl_result {
            close_returned_fd(new_dmabuf.fd);
            return Err(io::Error::from(error));
        }

        let fd = new_dmabuf.fd;
        if fd < 0 {
            return Err(io::Error::other(
                "Invalid fd returned from VIRTWL_IOCTL_NEW_DMABUF",
            ));
        }

        let layout = new_dmabuf.get_dmabuf();
        if layout.stride0 == 0 {
            close_returned_fd(fd);
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                "VirtWL dma-buf returned a zero plane-0 stride",
            ));
        }

        Ok((
            unsafe { OwnedFd::from_raw_fd(fd) },
            VirtWaylandDmabufLayout {
                strides: [layout.stride0, layout.stride1, layout.stride2],
                offsets: [layout.offset0, layout.offset1, layout.offset2],
            },
        ))
    }

    /// Synchronize CPU access to a VirtWL dma-buf.
    ///
    /// VirtWL exposes the same begin/end read/write contract as
    /// `DMA_BUF_IOCTL_SYNC`.  A failed begin or end must be surfaced to the
    /// caller; silently copying after a failed begin can race the host
    /// compositor and produce torn frames.
    pub fn sync(&self, dmabuf_fd: RawFd, flags: u32) -> io::Result<()> {
        if dmabuf_fd < 0 {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                "invalid VirtWL dma-buf descriptor",
            ));
        }
        let valid_flags = DMA_BUF_SYNC_READ | DMA_BUF_SYNC_WRITE | DMA_BUF_SYNC_END;
        if flags & !valid_flags != 0 || flags & (DMA_BUF_SYNC_READ | DMA_BUF_SYNC_WRITE) == 0 {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                "invalid VirtWL dma-buf sync flags",
            ));
        }
        let mut sync = crate::virtwl::virtwl_ioctl_dmabuf_sync { flags };
        unsafe { virtwl_ioctl_dmabuf_sync(dmabuf_fd, &mut sync) }
            .map(|_| ())
            .map_err(io::Error::from)
    }

    pub fn create_pipe(&self, read: bool) -> io::Result<OwnedFd> {
        let mut new_pipe = if read {
            crate::virtwl::virtwl_ioctl_new::new_pipe_read()
        } else {
            crate::virtwl::virtwl_ioctl_new::new_pipe_write()
        };

        let ioctl_result = unsafe { virtwl_ioctl_new(self.dev_file.as_raw_fd(), &mut new_pipe) };
        if let Err(error) = ioctl_result {
            close_returned_fd(new_pipe.fd);
            return Err(io::Error::from(error));
        }

        let fd = new_pipe.fd;
        if fd < 0 {
            return Err(io::Error::other(
                "Invalid fd returned from VIRTWL_IOCTL_NEW_PIPE",
            ));
        }

        Ok(unsafe { OwnedFd::from_raw_fd(fd) })
    }

    pub async fn send(&self, data: &[u8], fds: &[RawFd]) -> io::Result<()> {
        if fds.len() > VIRTWL_SEND_MAX_ALLOCS {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                "Too many file descriptors to send",
            ));
        }

        // A Unix socket read may contain several complete Wayland messages.
        // Keep the stream intact while splitting it into virtwl-sized
        // transactions. SCM_RIGHTS belongs to the beginning of the byte
        // stream, so pass the descriptors only with the first chunk.
        let chunks: Vec<&[u8]> = if data.is_empty() {
            vec![data]
        } else {
            data.chunks(MAX_SEND_SIZE).collect()
        };
        for (chunk_index, chunk) in chunks.into_iter().enumerate() {
            self.send_chunk(chunk, if chunk_index == 0 { fds } else { &[] })
                .await?;
        }
        Ok(())
    }

    async fn send_chunk(&self, data: &[u8], fds: &[RawFd]) -> io::Result<()> {
        let header_size = std::mem::size_of::<virtwl_ioctl_txn>();
        let total_bytes = header_size + data.len();

        // Use Vec<u32> to guarantee 4-byte alignment for virtwl_ioctl_txn
        let mut buf: Vec<u32> = vec![0u32; total_bytes.div_ceil(4)];

        {
            let buf_ptr = buf.as_mut_ptr() as *mut u8;
            let txn = unsafe { &mut *(buf_ptr as *mut virtwl_ioctl_txn) };

            txn.len = data.len() as u32;
            for (i, fd) in fds.iter().enumerate() {
                txn.fds[i] = *fd;
            }
            // Fill remaining FDs with -1
            for i in fds.len()..VIRTWL_SEND_MAX_ALLOCS {
                txn.fds[i] = -1;
            }

            // Copy data after header
            unsafe {
                std::ptr::copy_nonoverlapping(data.as_ptr(), buf_ptr.add(header_size), data.len());
            }
        }

        loop {
            let mut guard = self.ctx_fd.writable().await?;
            let res = guard.try_io(|inner| {
                let buf_ptr = buf.as_mut_ptr() as *mut u8;
                // virtwl_ioctl_send is generated by ioctl_read! and takes *mut virtwl_ioctl_txn
                unsafe {
                    virtwl_ioctl_send(inner.as_raw_fd(), buf_ptr as *mut virtwl_ioctl_txn)
                        .map_err(io::Error::from)
                }
            });

            match res {
                Ok(Ok(_)) => return Ok(()),
                Ok(Err(e)) => return Err(e),
                Err(_would_block) => continue,
            }
        }
    }

    pub async fn recv(&self) -> io::Result<(Vec<u8>, Vec<OwnedFd>)> {
        let header_size = std::mem::size_of::<virtwl_ioctl_txn>();
        let buf_size_bytes = header_size + MAX_SEND_SIZE;

        // Use Vec<u32> to guarantee 4-byte alignment for virtwl_ioctl_txn
        let mut buf: Vec<u32> = vec![0u32; buf_size_bytes.div_ceil(4)];

        loop {
            let mut guard = self.ctx_fd.readable().await?;
            let res = guard.try_io(|inner| {
                let buf_ptr = buf.as_mut_ptr() as *mut u8;
                let txn = unsafe { &mut *(buf_ptr as *mut virtwl_ioctl_txn) };
                txn.len = MAX_SEND_SIZE as u32;
                txn.fds.fill(-1); // Prevent reading uninitialized or previous FDs

                // virtwl_ioctl_recv is generated by ioctl_write_ptr! and takes *const virtwl_ioctl_txn.
                // Even though it takes *const, the kernel WRITES to it (because of _IOW direction quirk).
                // So we pass our mutable buffer cast to const.
                unsafe {
                    virtwl_ioctl_recv(
                        inner.as_raw_fd(),
                        txn as *mut virtwl_ioctl_txn as *const virtwl_ioctl_txn,
                    )
                    .map_err(io::Error::from)
                }
            });

            match res {
                Ok(Ok(_)) => {
                    let buf_ptr = buf.as_mut_ptr() as *mut u8;
                    let txn = unsafe { &*(buf_ptr as *const virtwl_ioctl_txn) };
                    let data_len = txn.len as usize;
                    if data_len > MAX_SEND_SIZE {
                        close_raw_fds(&txn.fds);
                        return Err(io::Error::new(
                            io::ErrorKind::InvalidData,
                            "Received data too large",
                        ));
                    }

                    let data_slice =
                        unsafe { std::slice::from_raw_parts(buf_ptr.add(header_size), data_len) };
                    let data = data_slice.to_vec();

                    let fds = owned_fds_from_txn(&txn.fds)?;

                    return Ok((data, fds));
                }
                Ok(Err(e)) => {
                    // The ChromiumOS virtwl driver normally returns without
                    // publishing descriptors when recv fails. Treat the
                    // transaction buffer as an untrusted device boundary
                    // nevertheless: an alternate implementation may have
                    // allocated VFDs before reporting a later error. Any
                    // descriptor it wrote is owned by this channel and must
                    // not survive the failed receive.
                    let buf_ptr = buf.as_mut_ptr() as *const u8;
                    let txn = unsafe { &*(buf_ptr as *const virtwl_ioctl_txn) };
                    close_raw_fds(&txn.fds);
                    return Err(e);
                }
                Err(_would_block) => continue,
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{
        add_nonblocking_flag, close_raw_fds, close_returned_fd, dmabuf_probe_supported,
        owned_fds_from_txn, DEFAULT_BUFFER_SIZE, MAX_SEND_SIZE,
    };
    use crate::virtwl::virtwl_ioctl_txn;
    use nix::fcntl::OFlag;
    use std::os::fd::AsRawFd;

    #[test]
    fn max_send_size_leaves_room_for_ioctl_header() {
        assert_eq!(
            MAX_SEND_SIZE + std::mem::size_of::<virtwl_ioctl_txn>(),
            DEFAULT_BUFFER_SIZE
        );
        const {
            assert!(MAX_SEND_SIZE < DEFAULT_BUFFER_SIZE);
        }
    }

    #[test]
    fn adding_nonblocking_preserves_existing_file_status_flags() {
        let existing = OFlag::O_APPEND | OFlag::O_ASYNC;
        let updated = add_nonblocking_flag(existing);
        assert!(updated.contains(OFlag::O_APPEND));
        assert!(updated.contains(OFlag::O_ASYNC));
        assert!(updated.contains(OFlag::O_NONBLOCK));
    }

    #[test]
    fn dmabuf_probe_only_rejects_missing_ioctl_support() {
        assert!(dmabuf_probe_supported(None));
        assert!(dmabuf_probe_supported(Some(libc::EINVAL)));
        assert!(!dmabuf_probe_supported(Some(libc::ENOTTY)));
    }

    #[test]
    fn dmabuf_layout_preserves_all_returned_planes() {
        let layout = super::VirtWaylandDmabufLayout {
            strides: [4096, 2048, 0],
            offsets: [0, 4096 * 1080, 0],
        };
        assert_eq!(layout.strides, [4096, 2048, 0]);
        assert_eq!(layout.offsets, [0, 4096 * 1080, 0]);
    }

    #[test]
    fn returned_ioctl_fd_is_closed_on_error_paths() {
        let mut pipe_fds = [-1; 2];
        assert_eq!(unsafe { libc::pipe(pipe_fds.as_mut_ptr()) }, 0);
        let returned_fd = unsafe { libc::fcntl(pipe_fds[1], libc::F_DUPFD_CLOEXEC, 1000) };
        assert!(returned_fd >= 1000);
        unsafe {
            libc::close(pipe_fds[0]);
            libc::close(pipe_fds[1]);
        }

        close_returned_fd(returned_fd);
        assert_eq!(unsafe { libc::fcntl(returned_fd, libc::F_GETFD) }, -1);
    }

    #[test]
    fn recv_ioctl_error_closes_descriptors_written_before_failure() {
        let mut pipe_fds = [-1; 2];
        assert_eq!(unsafe { libc::pipe(pipe_fds.as_mut_ptr()) }, 0);
        let returned_fd = unsafe { libc::fcntl(pipe_fds[1], libc::F_DUPFD_CLOEXEC, 1000) };
        assert!(returned_fd >= 1000);
        unsafe {
            libc::close(pipe_fds[0]);
            libc::close(pipe_fds[1]);
        }

        // Model a device that wrote a descriptor and then returned an ioctl
        // error. The receive error branch must reclaim it before propagating
        // the error.
        let mut txn = virtwl_ioctl_txn {
            fds: [-1; crate::virtwl::VIRTWL_SEND_MAX_ALLOCS],
            len: 0,
        };
        txn.fds[0] = returned_fd;
        close_raw_fds(&txn.fds);

        assert_eq!(unsafe { libc::fcntl(returned_fd, libc::F_GETFD) }, -1);
        unsafe {
            libc::close(pipe_fds[1]);
        }
    }

    #[test]
    fn virtwl_fd_array_must_be_packed() {
        let mut pipe_fds = [-1; 2];
        assert_eq!(unsafe { libc::pipe(pipe_fds.as_mut_ptr()) }, 0);
        // Keep the descriptor out of the low-numbered range used by other
        // tests. `owned_fds_from_txn` closes malformed arrays immediately;
        // a parallel test must not be able to reuse the just-closed number
        // before the assertion below checks it.
        let returned_fd = unsafe { libc::fcntl(pipe_fds[1], libc::F_DUPFD_CLOEXEC, 1000) };
        assert!(returned_fd >= 1000);
        unsafe {
            libc::close(pipe_fds[1]);
        }
        let invalid = [-1, returned_fd];
        assert!(owned_fds_from_txn(&invalid).is_err());
        assert_eq!(unsafe { libc::fcntl(returned_fd, libc::F_GETFD) }, -1);
        unsafe {
            libc::close(pipe_fds[0]);
        }
    }

    #[test]
    fn virtwl_fd_array_rejects_negative_values_other_than_sentinel() {
        let invalid = [-2, -1];
        assert!(owned_fds_from_txn(&invalid).is_err());
    }

    #[test]
    fn virtwl_fd_array_converts_packed_descriptors_to_owned_fds() {
        let mut pipe_fds = [-1; 2];
        assert_eq!(unsafe { libc::pipe(pipe_fds.as_mut_ptr()) }, 0);
        let raw = [pipe_fds[1], -1];
        let owned = owned_fds_from_txn(&raw).expect("packed fd array");
        assert_eq!(owned.len(), 1);
        assert_eq!(owned[0].as_raw_fd(), pipe_fds[1]);
        drop(owned);
        unsafe {
            libc::close(pipe_fds[0]);
        }
    }
}
